[package]
name = "rvx-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
crossterm.workspace = true
instability.workspace = true
ratatui.workspace = true
reqwest.workspace = true
rvx-config = { path = "../rvx-config" }
serde_json.workspace = true
tokio.workspace = true
url.workspace = true
unicode-segmentation.workspace = true

[dev-dependencies]
toml.workspace = true

[[bin]]
name = "rvx"
path = "src/main.rs"
