[package]
name = "rvx-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
arrow.workspace = true
crc32fast.workspace = true
futures.workspace = true
libc.workspace = true
rvx-core = { path = "../rvx-core" }
parking_lot.workspace = true
parquet.workspace = true
reqwest.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
smallvec.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
axum.workspace = true
